apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${{ values.clusterName }}
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.0.0.0/16"]
    services:
      cidrBlocks: ["10.128.0.0/12"]
    serviceDomain: "cluster.local"
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: ${{ values.clusterName }}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: ${{ values.clusterName }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: ${{ values.clusterName }}
  namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: ${{ values.clusterName }}-control-plane
  namespace: default
spec:
  resourceGroupName: rg-${{ values.clusterName }}
  location: ${{ values.region }}
  subscriptionID: ${{ values.subscriptionId }}
  version: ${{ values.kubernetesVersion }}
  networkPolicy: azure # or calico/cilium
  networkPlugin: azure # or kubenet
  networkDataplane: cilium
  loadBalancerSKU: Standard
  identityRef:
    kind: AzureClusterIdentity
    name: cluster-identity
  enablePreviewFeatures: true
  oidcIssuerProfile:
    enabled: true
  securityProfile:
    workloadIdentity:
      enabled: true
    imageCleaner:
      enabled: true
      intervalHours: 24
  sku:
    tier: Free
  addonProfiles:
    azureKeyvaultSecretsProvider:
      enabled: true
    azurepolicy:
      enabled: true
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: system
spec:
  clusterName: ${{ values.clusterName }}
  replicas: ${{ values.nodeCount }}
  template:
    spec:
      clusterName: ${{ values.clusterName }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: system
        namespace: default
      version: ${{ values.kubernetesVersion }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: system
spec:
  mode: System
  osDiskSizeGB: 30
  sku: ${{ values.nodeSku }}
  availabilityZones: ["1", "2", "3"]
