apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${{ values.clusterName }}
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.0.0.0/16"]
    services:
      cidrBlocks: ["10.128.0.0/12"]
    serviceDomain: "cluster.local"
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: ${{ values.clusterName }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: ${{ values.clusterName }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: ${{ values.clusterName }}
  namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: ${{ values.clusterName }}
  namespace: default
spec:
  resourceGroupName: rg-${{ values.clusterName }}
  location: ${{ values.region }}
  subscriptionID: ${{ values.subscriptionId }}
  version: ${{ values.kubernetesVersion }}
  networkPolicy: cilium
  networkPlugin: azure
  networkPluginMode: overlay
  networkDataplane: cilium
  loadBalancerSKU: Standard
  identityRef:
    kind: AzureClusterIdentity
    name: cluster-identity
  enablePreviewFeatures: false
  oidcIssuerProfile:
    enabled: true
  securityProfile:
    workloadIdentity:
      enabled: true
    imageCleaner:
      enabled: true
      intervalHours: 24
  sku:
    tier: Free
  addonProfiles:
  - name: azureKeyvaultSecretsProvider
    enabled: true
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: system
  namespace: default
spec:
  clusterName: ${{ values.clusterName }}
  replicas: 2
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: "azure-managed"
      clusterName: ${{ values.clusterName }}
      version: ${{ values.kubernetesVersion }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: system
        namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: system
  namespace: default
spec:
  mode: System
  osDiskSizeGB: 30
  osDiskType: Ephemeral
  sku: Standard_D2pds_v5
  availabilityZones:
    - "1"
    - "2"
    - "3"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: app
  namespace: default
spec:
  clusterName: ${{ values.clusterName }}
  replicas: ${{ values.nodeCount }}
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: "azure-managed"
      clusterName: ${{ values.clusterName }}
      version: ${{ values.kubernetesVersion }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: app
        namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: app
  namespace: default
spec:
  mode: User
  osDiskSizeGB: 30
  osDiskType: Ephemeral
  sku: ${{ values.nodeSku }}
  availabilityZones:
    - "1"
    - "2"
    - "3"