apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-kubernetes-cluster-template
  title: Create an Azure Kubernetes Cluster
  description: Deploy a Kubernetes cluster to Azure.
spec:
  owner: guest
  type: infrastructure

  parameters:
    - title: Azure Configuration
      required:
        - subscriptionId
        - clusterName
        - kubernetesVersion
        - nodeSku
        - nodeCount
      properties:
        clusterName:
          title: Cluster Name
          type: string
          description: Name of the Kubernetes cluster
          pattern: '^[a-z0-9]([a-z0-9\-_.]*[a-z0-9])?$'
          minLength: 1
          maxLength: 63

        subscriptionId:
          title: Azure Subscription
          type: string
          description: Select the Azure subscription to deploy the cluster in
          enum:
            - f645938d-2368-4a99-b589-ea72e5544719
            - b8aa5c3e-0d9b-4825-93e5-527ced1b4503
          ui:options:
            enumNames:
              - AzureSandbox
              - AzureProduction
          default: f645938d-2368-4a99-b589-ea72e5544719

        region:
          title: Azure Region
          type: string
          description: Region to deploy the cluster in
          enum:
            - eastus
            - eastus2
            - centralus
          default: eastus

        kubernetesVersion:
          title: Kubernetes Version
          type: string
          enum:
            - 1.32.3
            - 1.31.7
            - 1.30.11
          default: 1.30.11

        nodeSku:
          title: Node SKU Type
          type: string
          description: Azure VM size for the nodes
          ui:options:
            enumNames:
              - Standard_D2pds_v5 (2 vCPUs, 8 GiB memory)
              - Standard_D4pds_v5 (4 vCPUs, 16 GiB memory)
              - Standard_D8pds_v5 (8 vCPUs, 32 GiB memory)
          enum:
            - Standard_D2pds_v5
            - Standard_D4pds_v5
            - Standard_D8pds_v5
          default: Standard_D2pds_v5

        nodeCount:
          title: Node Count
          type: integer
          description: Number of worker nodes
          default: 3
          minimum: 1
          maximum: 100

    - title: Git Repository
      required:
        - repoUrl
        - branch
      properties:
        repoUrl:
          title: Repository URL
          type: string
          default: github.com?repo=azure-cluster-api&owner=jaredthivener
          description: Git repository for Flux CD to monitor
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

        branch:
          title: Git Branch
          type: string
          default: main
          description: Branch to commit to in the repository

  steps:
    - id: fetch-template
      name: Render Cluster YAML
      action: fetch:template
      input:
        url: https://github.com/jaredthivener/azure-cluster-api/tree/main/templates/aks-clusters/skeleton
        values:
          clusterName:        ${{ parameters.clusterName }}
          region:             ${{ parameters.region }}
          kubernetesVersion:  ${{ parameters.kubernetesVersion }}
          subscriptionId:     ${{ parameters.subscriptionId }}
          nodeSku:            ${{ parameters.nodeSku }}
          nodeCount:          ${{ parameters.nodeCount }}
          resourceGroup:      ${{ parameters.clusterName }}
        targetPath: ./content

    - id: debug-list-content
      name: List content directory
      action: debug:log
      input:
        listWorkspace: true

    - id: remove-catalog-info
      name: Remove catalog info file
      action: fs:delete
      input:
        files:
          - ./content/catalog-info.yaml

    - id: publish-cluster
      name: Publish Cluster YAML
      action: publish:github:pull-request
      input:
        repoUrl:     ${{ parameters.repoUrl }}
        branchName:  cluster-api/${{ parameters.clusterName }}
        title:       "Add Cluster YAML for ${{ parameters.clusterName }}"
        description: "Automated PR from Backstage template"
        sourcePath:  ./content
        targetPath:  clusters/${{ parameters.clusterName }}
        update:      true

  output:
    links:
      - title: Repository
        url: ${{ steps['publish-cluster'].output.remoteUrl }}
