name: Infrastructure CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'infra/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add infrastructure validation steps here
